namespace LibCK3.Models
{
    [CK3SaveGameVersion("1.4.4")]

    public class Genes
    {
        public int[] hair_color { get; set; }
        public int[] skin_color { get; set; }
        public int[] eye_color { get; set; }
        public object[] gene_chin_forward { get; set; }
        public object[] gene_chin_height { get; set; }
        public object[] gene_chin_width { get; set; }
        public object[] gene_eye_angle { get; set; }
        public object[] gene_eye_depth { get; set; }
        public object[] gene_eye_height { get; set; }
        public object[] gene_eye_distance { get; set; }
        public object[] gene_eye_shut { get; set; }
        public object[] gene_forehead_angle { get; set; }
        public object[] gene_forehead_brow_height { get; set; }
        public object[] gene_forehead_roundness { get; set; }
        public object[] gene_forehead_width { get; set; }
        public object[] gene_forehead_height { get; set; }
        public object[] gene_head_height { get; set; }
        public object[] gene_head_width { get; set; }
        public object[] gene_head_profile { get; set; }
        public object[] gene_head_top_height { get; set; }
        public object[] gene_head_top_width { get; set; }
        public object[] gene_jaw_angle { get; set; }
        public object[] gene_jaw_forward { get; set; }
        public object[] gene_jaw_height { get; set; }
        public object[] gene_jaw_width { get; set; }
        public object[] gene_mouth_corner_depth { get; set; }
        public object[] gene_mouth_corner_height { get; set; }
        public object[] gene_mouth_forward { get; set; }
        public object[] gene_mouth_height { get; set; }
        public object[] gene_mouth_width { get; set; }
        public object[] gene_mouth_upper_lip_size { get; set; }
        public object[] gene_mouth_lower_lip_size { get; set; }
        public object[] gene_mouth_open { get; set; }
        public object[] gene_neck_length { get; set; }
        public object[] gene_neck_width { get; set; }
        public object[] gene_bs_cheek_forward { get; set; }
        public object[] gene_bs_cheek_height { get; set; }
        public object[] gene_bs_cheek_width { get; set; }
        public object[] gene_bs_ear_angle { get; set; }
        public object[] gene_bs_ear_inner_shape { get; set; }
        public object[] gene_bs_ear_bend { get; set; }
        public object[] gene_bs_ear_outward { get; set; }
        public object[] gene_bs_ear_size { get; set; }
        public object[] gene_bs_eye_corner_depth { get; set; }
        public object[] gene_bs_eye_fold_shape { get; set; }
        public object[] gene_bs_eye_size { get; set; }
        public object[] gene_bs_eye_upper_lid_size { get; set; }
        public object[] gene_bs_forehead_brow_curve { get; set; }
        public object[] gene_bs_forehead_brow_forward { get; set; }
        public object[] gene_bs_forehead_brow_inner_height { get; set; }
        public object[] gene_bs_forehead_brow_outer_height { get; set; }
        public object[] gene_bs_forehead_brow_width { get; set; }
        public object[] gene_bs_jaw_def { get; set; }
        public object[] gene_bs_mouth_lower_lip_def { get; set; }
        public object[] gene_bs_mouth_lower_lip_full { get; set; }
        public object[] gene_bs_mouth_lower_lip_pad { get; set; }
        public object[] gene_bs_mouth_lower_lip_width { get; set; }
        public object[] gene_bs_mouth_philtrum_def { get; set; }
        public object[] gene_bs_mouth_philtrum_shape { get; set; }
        public object[] gene_bs_mouth_philtrum_width { get; set; }
        public object[] gene_bs_mouth_upper_lip_def { get; set; }
        public object[] gene_bs_mouth_upper_lip_full { get; set; }
        public object[] gene_bs_mouth_upper_lip_profile { get; set; }
        public object[] gene_bs_mouth_upper_lip_width { get; set; }
        public object[] gene_bs_nose_forward { get; set; }
        public object[] gene_bs_nose_height { get; set; }
        public object[] gene_bs_nose_length { get; set; }
        public object[] gene_bs_nose_nostril_height { get; set; }
        public object[] gene_bs_nose_nostril_width { get; set; }
        public object[] gene_bs_nose_profile { get; set; }
        public object[] gene_bs_nose_ridge_angle { get; set; }
        public object[] gene_bs_nose_ridge_width { get; set; }
        public object[] gene_bs_nose_size { get; set; }
        public object[] gene_bs_nose_tip_angle { get; set; }
        public object[] gene_bs_nose_tip_forward { get; set; }
        public object[] gene_bs_nose_tip_width { get; set; }
        public object[] face_detail_cheek_def { get; set; }
        public object[] face_detail_cheek_fat { get; set; }
        public object[] face_detail_chin_cleft { get; set; }
        public object[] face_detail_chin_def { get; set; }
        public object[] face_detail_eye_lower_lid_def { get; set; }
        public object[] face_detail_eye_socket { get; set; }
        public object[] face_detail_nasolabial { get; set; }
        public object[] face_detail_nose_ridge_def { get; set; }
        public object[] face_detail_nose_tip_def { get; set; }
        public object[] face_detail_temple_def { get; set; }
        public object[] expression_brow_wrinkles { get; set; }
        public object[] expression_eye_wrinkles { get; set; }
        public object[] expression_forehead_wrinkles { get; set; }
        public object[] expression_other { get; set; }
        public object[] complexion { get; set; }
        public object[] gene_height { get; set; }
        public object[] gene_bs_body_type { get; set; }
        public object[] gene_bs_body_shape { get; set; }
        public object[] gene_bs_bust { get; set; }
        public object[] gene_age { get; set; }
        public object[] gene_eyebrows_shape { get; set; }
        public object[] gene_eyebrows_fullness { get; set; }
        public object[] gene_body_hair { get; set; }
        public object[] gene_hair_type { get; set; }
        public object[] gene_baldness { get; set; }
        public object[] eye_accessory { get; set; }
        public object[] teeth_accessory { get; set; }
        public object[] eyelashes_accessory { get; set; }
        public object[] pose { get; set; }
        public object[] beards { get; set; }
        public object[] cloaks { get; set; }
        public object[] gene_bs_cloak { get; set; }
        public object[] clothes { get; set; }
        public object[] hairstyles { get; set; }
        public object[] headgear { get; set; }
        public object[] legwear { get; set; }
    }
}
