name: dotnet package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Download test assets
      run: |
         wget ${{secrets.CK3_TEST_ASSETS_URL}} -q -O assets.zip
         unzip assets.zip -x '/' -d test/LibCK3.Tests/assets/
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --no-build --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Pack
      run: dotnet pack --no-restore --no-build --output pkg
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
          name: LibCK3-pkg
          path: pkg/*.*
